name: Record Video

on:
  workflow_dispatch:

jobs:
  record:
    runs-on: self-hosted
    # ... reste du workflow ...
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Record video
      run: python record_video.py
    - name: Upload video
      uses: actions/upload-artifact@v2
      with:
        name: recorded-video
        path: video_*.avi
